name : Test fact

on : 

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
   build:
    name: Test Build
    runs-on: ubuntu-latest
    steps: 
    - name: Set up Go 1.x 
      uses: actions/setup-go@v2
      with :
        go-version: ^1.13

    - name : Check out code into the Go module directory
      uses: actions/checkout@v2


    - name : build 
      run : make install
    

    - name: Test
      run: make test
